name: Build & deploy ASP.NET Core app to Azure Web App - rahmanmembervault-api

on:
  push:
    branches:
      - dev_mustafiz
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore & build solution
        run: |
          dotnet restore RahmanMemberVault.sln
          dotnet build   RahmanMemberVault.sln --configuration Release

      - name: Publish Web API
        run: |
          dotnet publish RahmanMemberVault.Api/RahmanMemberVault.Api.csproj \
            --configuration Release \
            --output ${{ runner.workspace }}/publish

      - name: Inspect publish folder
        run: |
          echo "=== publish folder contents ==="
          ls -R ${{ runner.workspace }}/publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-publish
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: Production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-publish
          path: publish

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5C65ABF0753E4BFE8FE331D08D20076F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B37DD792DF8442FE86DCA690F425BD47 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FBEA32F4FDE9467AA49521F2E87D7669 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name:   'rahmanmembervault-api'
          slot-name:  'Production'
          package:    publish
          clean:      true
